[package]
name = "birdsite-creds"
authors = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
regex = { workspace = true }
serde = { workspace = true }
