[package]
name = "birdsite-hacks"
workspace = ".."
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
archivindex-wbm = { git = "ssh://git@github.com/travisbrown/archivindex.git" }
archivindex-wbm-json = { git = "ssh://git@github.com/travisbrown/archivindex.git" }
archivindex-wbm-json-processing = { git = "ssh://git@github.com/travisbrown/archivindex.git" }
birdsite = { path = "../core/" }
bounded-static = { workspace = true }
chrono = { workspace = true }
cli-helpers = "0.1"
csv = "1"
futures = "0.3"
globwalk = "0.9"
itertools = "0.15"
rocksdb = { version = "0.24", features = ["zstd"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
zstd = "0.13"
